### ISSUE TITLE
Добавить пакет на packagist.org

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/SimpleTab#1]
Залить пару файлов конечно не сложно, но если в проекте требуется разработка модуля/плагина под задачу и есть опыт работы с composer, то установка будет еще проще.

**Comment by AgelxNash** [comment]
Либо как вариант перенести файлы репозиторий https://github.com/AgelxNash/DocLister, т.к. этот пакет напрямую от него зависит.

**Comment by Pathologic** [comment]
Давай пока перенесем в DocLister. Я правильно понимаю, что реальной работы там больше, чем просто пакет залить - еще, как минимум, указать зависимости, поубирать include/require классов?

**Comment by AgelxNash** [comment]
Ну по факту - да. Там и с путями вопрос будет открытый, и конфликт классов возможен, если потом вдруг потребуется еще поставить SimpleGallery например.

Пришли PR если не сложно. Я приму оперативненько это дело, а потом, как время/желание появится - покроем тестами:-)

**Comment by AgelxNash** [comment]
Перенес. Только JavaScript из папки assets/lib/SimpleTab/js переместил в assets/js. Все-таки они могут понадобиться не только для SimpleTab плагинов. Допустим FileAPI используется и в redirectMap2 модуле. Сейчас пришлю PR в SimpleGallery с обновлением путей к скриптам.

**Comment by Pathologic** [comment]
Не очень мне нравится assets/js - файлы там могут перезаписываться без учета версий и что-нибудь поломается или в админке, или во фронте.

**Comment by AgelxNash** [comment]
Оно как бы и правильно, но есть большое и жирное **НО**:
 - FileAPI используется в SimpleGallery. Этот же скрипт может понадобиться и в каком-нибудь плагине (*допустим, кастомный ТВ для добавления картинки к документу Drag&Drop'ом*). Я дико сомневаюсь, что 2 разных версии одного и того же компонента будут способны ужиться друг с другом в пределах одной страницы.
 - За обратной совместимостью должен следить разработчик скрипта. А если он игнорирует это правило систематически - то такой скрипт вообще не желательно использовать. В случае же, если разработчик старается сохранять обратную совместимость - то ничего страшного не произойдет. Но даже если что-то и радикально изменилось - то нужно просто уделить время на обновление и устранение несовместимости.

Поэтому даже если вдруг какой-то другой компонент/юзер зальет в assets/js более новую версию скрипта используемого тем же SimpleGallery, то лучшим решением будет переход со старой версии на новую в рамках SimpleGallery.
Если же зальют старье - то нужно слать багрепорт/PR в компонент работающий со старой версией и предлагать переходить на новую версию. А если это по инициативе пользователя - то его проблемы. Пусть либо переходит на новую версию, либо переносит старье в другое место, либо отказывается от функционала который был сломан в результате этого даунгрейда.

Так что я особой проблемы тут не вижу.
